import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const SITE='https://jamesrealty.uk';
const UPDATED='2026-09-01';
const VERSION='20260901-advisory-1';

const projects=[
  {name:'Golf Vale',developer:'Emaar',location:'Emaar South',status:'Opportunity to Review',stage:'Off-plan',type:'Apartment',budget:'1-2m',price:'Published reference from AED 1.09m',handover:'Confirm current release',image:'/images/projects/emaar-golf-community-apartments.webp',source:'https://emaar.jamesrealty.uk/',why:'Lower-entry Emaar research route in a growing master community.',risk:'The published starting price does not confirm an available unit, view, floor or total acquisition cost.',buyer:'Buyers prioritising developer track record and a longer community-growth horizon.'},
  {name:'Creek Bay',developer:'Emaar',location:'Dubai Creek Harbour',status:'Opportunity to Review',stage:'Off-plan',type:'Apartment',budget:'1-2m',price:'Published reference from AED 1.80m',handover:'Confirm current release',image:'/images/projects/emaar-waterfront-marina-residences.webp',source:'https://emaar.jamesrealty.uk/',why:'Waterfront master-community option with an established Emaar research trail.',risk:'Test the waterfront premium, service charges, surrounding delivery and same-building competition.',buyer:'Buyers who value a planned waterfront district and accept off-plan delivery risk.'},
  {name:'Yas Park Place',developer:'Aldar',location:'Yas Island',status:'Developer Portfolio',stage:'Off-plan',type:'Villa|Townhouse',budget:'on-request',price:'Price and release on request',handover:'Confirm phase and contract',image:'/images/projects/aldar-yas-waterfront-apartments.webp',source:'https://aldar.jamesrealty.uk/',why:'Family-led Yas Island route inside Aldar’s Abu Dhabi portfolio.',risk:'Compare phase, plot, school access, future supply and commute before paying an island premium.',buyer:'End users and long-hold buyers considering Yas Island family communities.'},
  {name:'The Wilds Residences',developer:'Aldar',location:'Dubai',status:'Opportunity to Review',stage:'Off-plan',type:'Villa|Townhouse',budget:'on-request',price:'Availability on request',handover:'Confirm current release',image:'/images/projects/aldar-nature-led-villas.webp',source:'https://aldar.jamesrealty.uk/',why:'Aldar’s Dubai expansion route for buyers comparing nature-led family products.',risk:'Review the exact Dubai location, delivery sequence and Aldar’s project-level execution outside Abu Dhabi.',buyer:'Family buyers open to a newer master-community proposition.'},
  {name:'DAMAC Islands 2',developer:'DAMAC',location:'Dubai',status:'Current Launch',stage:'Off-plan',type:'Villa|Townhouse',budget:'2-5m',price:'Published reference from AED 2.99m',handover:'Confirm cluster and phase',image:'/images/projects/damac-lagoon-villa-community.webp',source:'https://damac.jamesrealty.uk/',why:'Large-format villa and townhouse proposition with a published entry reference.',risk:'Model masterplan delivery, infrastructure timing, density and competing future supply.',buyer:'Buyers seeking a themed family community and staged payment structure.'},
  {name:'Chelsea Residences',developer:'DAMAC',location:'Dubai Maritime City',status:'Developer Portfolio',stage:'Off-plan',type:'Apartment',budget:'on-request',price:'Availability on request',handover:'Confirm tower and unit',image:'/images/projects/damac-sea-view-residences.webp',source:'https://damac.jamesrealty.uk/',why:'Branded waterfront apartment route for buyers comparing lifestyle-led developments.',risk:'Test the brand premium, service charges, usable layout, maritime-city supply and rental audience.',buyer:'Lifestyle or international buyers comfortable underwriting a branded premium.'},
  {name:'Skyflame',developer:'Binghatti',location:'Dubai',status:'Opportunity to Review',stage:'Off-plan',type:'Apartment',budget:'under-1m',price:'Published reference from AED 585k',handover:'Confirm unit and schedule',image:'/images/projects/binghatti-crystalline-apartments.webp',source:'https://binghatti.jamesrealty.uk/',why:'Lower published entry route within Binghatti’s active Dubai portfolio.',risk:'Lower entry prices can mean compact units, higher density and stronger rental competition; inspect the exact stack.',buyer:'Budget-conscious investors who will compare net yield and unit efficiency.'},
  {name:'Luxuria',developer:'Binghatti',location:'Dubai',status:'Opportunity to Review',stage:'Off-plan',type:'Apartment',budget:'under-1m',price:'Published reference from AED 765,999',handover:'Confirm current release',image:'/images/projects/binghatti-copper-geometric-tower.webp',source:'https://binghatti.jamesrealty.uk/',why:'Binghatti apartment comparison point with a published starting reference.',risk:'Verify current availability, unit size, payment schedule, service charges and local competing supply.',buyer:'Investors comparing entry cost, developer delivery and rental-market depth.'},
  {name:'Palm Central',developer:'Nakheel',location:'Palm Jebel Ali',status:'Developer Portfolio',stage:'Off-plan',type:'Apartment|Villa',budget:'on-request',price:'Availability on request',handover:'Confirm infrastructure phase',image:'/images/projects/nakheel-private-island-villas.webp',source:'https://nakheel.jamesrealty.uk/',why:'Long-horizon waterfront route inside a strategically important Nakheel masterplan.',risk:'Infrastructure, plot location, delivery sequence and holding costs matter more than the Palm name alone.',buyer:'Long-hold waterfront buyers with tolerance for a multi-phase district build-out.'},
  {name:'Bay Grove',developer:'Nakheel',location:'Dubai Islands',status:'Developer Portfolio',stage:'Off-plan',type:'Apartment',budget:'on-request',price:'Availability on request',handover:'Confirm current release',image:'/images/projects/nakheel-beachfront-tower.webp',source:'https://nakheel.jamesrealty.uk/',why:'Beachfront apartment route within the expanding Dubai Islands programme.',risk:'Compare island access, beach orientation, service charges, construction context and competing supply.',buyer:'Waterfront apartment buyers assessing a developing island district.'},
  {name:'Mudon Al Ranim',developer:'Dubai Properties',location:'Mudon',status:'Opportunity to Review',stage:'Off-plan',type:'Townhouse|Villa',budget:'on-request',price:'Availability on request',handover:'Confirm phase',image:'/images/projects/mudon-family-townhouses.webp',source:'https://mudon.jamesrealty.uk/',why:'Family townhouse and villa route in a community with ready-home comparables.',risk:'Compare phases, plot, park exposure, build specification and simultaneous resale listings.',buyer:'Families prioritising community maturity, parks and practical living space.'},
  {name:'Arabella',developer:'Dubai Properties',location:'Mudon',status:'Developer Portfolio',stage:'Ready',type:'Townhouse|Villa',budget:'on-request',price:'Current listings require verification',handover:'Ready-home inspection required',image:'/images/projects/mudon-villa-street.webp',source:'https://mudon.jamesrealty.uk/',why:'Ready-community benchmark for comparing later Mudon phases.',risk:'Inspect condition, upgrades, plot, tenancy, maintenance history and price against registered comparables.',buyer:'End users who value inspection certainty and an established family community.'}
];

const areas=[
  {slug:'dubai-marina',name:'Dubai Marina',image:'/images/investors/usa-dubai-marina-apartment.webp',label:'Waterfront apartment district',profile:'Apartment buyers, lifestyle-led end users and investors who value established leasing demand.',transport:'Metro and tram access varies by building; marina traffic and walking distance should be tested at peak times.',schools:'Families usually compare schools outside the immediate marina district and model the daily commute.',supply:'A mature district, but building age, renovation cycles and nearby new waterfront stock can change relative value.',charges:'Service charges differ materially by tower, facilities and maintenance condition.',pros:['Established waterfront lifestyle','Broad apartment and tenant market','Metro, tram and walkability in selected locations'],cons:['Traffic and access vary by tower','Building quality and age are inconsistent','Service charges and holiday-home density need review']},
  {slug:'downtown-dubai',name:'Downtown Dubai',image:'/images/investors/uk-downtown-dubai-apartment.webp',label:'Prime central apartment district',profile:'International buyers and end users prioritising centrality, landmark views and a deep short- and long-let market.',transport:'Metro access is useful but walking distance, climate, event traffic and tower access should be checked.',schools:'Not primarily a school-led family district; compare nearby school routes and usable internal space.',supply:'Premium demand is deep, but new branded and central-Dubai launches compete for the same buyer pool.',charges:'High-amenity and branded towers can carry materially different service-charge structures.',pros:['Central Dubai location','Strong international recognition','Large range of apartment products'],cons:['View premiums can be difficult to recover','Event traffic and construction context vary','High service charges can reduce net yield']},
  {slug:'business-bay',name:'Business Bay',image:'/images/dubai-skyline-real-estate-social-v4.jpg',label:'Mixed-use central district',profile:'Investors and professionals comparing central access with a wide entry-price and building-quality range.',transport:'Metro proximity, canal crossings and last-mile access vary sharply between sub-locations.',schools:'Most family buyers commute to schools in neighbouring districts; journey time should be tested.',supply:'Large and varied pipeline; compare completion timing, developer concentration and competing unit types.',charges:'Mixed-use, canal and high-amenity towers require building-specific operating-cost review.',pros:['Central location beside Downtown','Wide range of prices and unit formats','Strong professional tenant audience'],cons:['Heavy future and current supply','Quality varies substantially by tower','Road access and walkability are uneven']},
  {slug:'dubai-hills-estate',name:'Dubai Hills Estate',image:'/images/investors/uk-dubai-hills-apartment.webp',label:'Planned family master community',profile:'Families, long-hold end users and investors comparing schools, parks, retail and newer stock.',transport:'Road access is the main consideration; test school, office and airport routes at realistic times.',schools:'School proximity is a central value driver, but catchments, fees and actual drive time must be verified.',supply:'Multiple apartment and villa phases create choice but also project-level competition.',charges:'Apartment service charges and villa maintenance should be modelled separately.',pros:['Strong family-community proposition','Newer stock and landscaped environment','Mix of apartments, townhouses and villas'],cons:['Car dependency remains significant','New supply can affect short-term resale competition','Master-community premiums require unit-level evidence']},
  {slug:'jumeirah-village-circle',name:'Jumeirah Village Circle',image:'/images/projects/binghatti-crystalline-apartments.webp',label:'High-supply apartment and townhouse district',profile:'Yield-focused investors, first-time buyers and residents comparing entry price with central Dubai access.',transport:'Road access is broad, but internal congestion, construction and walkability vary by sector.',schools:'Schools and nurseries exist within and around the district; exact access should be checked per building.',supply:'One of the most supply-sensitive areas; future completions and developer-level quality are essential checks.',charges:'Lower purchase price does not guarantee better net yield if charges, vacancy or maintenance are high.',pros:['Broad entry-price range','Large tenant and buyer pool','Many new apartment options'],cons:['High competing supply','Developer and build quality vary','Street-level environment differs materially by sector']},
  {slug:'palm-jumeirah',name:'Palm Jumeirah',image:'/images/landing/nakheel-dubai-island-waterfront.webp',label:'Prime waterfront apartment and villa market',profile:'High-net-worth end users and investors prioritising beachfront access, scarcity and global recognition.',transport:'Monorail and road access vary by frond, crescent and trunk; peak travel time should be tested.',schools:'Families generally travel off-island for schools, so commute and household logistics matter.',supply:'Scarcity is product-specific; new ultra-prime stock can reset asking prices without repricing older units equally.',charges:'Beachfront facilities, private amenities and branded services can produce substantial operating costs.',pros:['Globally recognised waterfront location','Distinct apartment, villa and branded segments','Strong lifestyle and international demand'],cons:['High entry and ownership costs','Access and construction context vary','Headline records are not normal-market comparables']}
];

const trackers=[
  {slug:'dubai-property-supply-tracker-2026',title:'Dubai Property Supply Tracker 2026',description:'A consolidated, source-led tracker for Dubai completions, delivery pipelines and the buyer implications of new housing supply.',kicker:'Dubai supply and delivery',intro:'Supply headlines matter only when they are connected to location, completion timing, unit type and realistic absorption. This tracker consolidates major 2026 updates instead of publishing repetitive short URLs.',updates:[
    ['21 Aug 2026','96,585 homes were reported in Dubai’s 2026 pipeline, with a large share described as sold','/blog/property-news-2026-08-21-dubai-has-96-585-homes-entering-the-market-in-2026-83-are-9eab9/'],
    ['20 Aug 2026','More than 24,000 new property units were reported over six months','/blog/property-news-2026-08-20-dubai-adds-more-than-24-000-property-units-in-six-months-5fb5c/'],
    ['1 Aug 2026','Dubai H1 handovers pointed to a more delivery-led market cycle','/blog/dubai-h1-2026-delivery-led-property-cycle/']
  ],checks:['Separate launches, construction and completed handovers.','Map supply to the same micro-market and property type.','Test rent, vacancy and resale competition under a conservative case.','Use project-level escrow, construction and contract checks before buying.']},
  {slug:'dubai-rental-market-tracker-2026',title:'Dubai Rental Market Tracker 2026',description:'A consolidated tracker for Dubai rental supply, payment changes, tenant conditions and evidence-led landlord or renter decisions.',kicker:'Dubai rents and tenant conditions',intro:'Rental headlines often mix payment innovation, building incidents and city-wide market claims. This page keeps those updates together and separates convenience from the economics of rent, vacancy and ownership.',updates:[
    ['13 Aug 2026','Monthly apartment-rent options expanded across the UAE','/blog/property-news-2026-08-13-uae-rental-update-what-tenants-and-landlords-should-verify-cbf17/'],
    ['13 Aug 2026','A rent-now-pay-later service promoted zero-interest instalments','/blog/property-news-2026-08-13-dubai-housing-supply-what-buyers-and-owners-should-check-n-8ca93/'],
    ['21 Aug 2026','A major tenant transition was reported at Dubai’s Toyota Building','/blog/property-news-2026-08-21-70-of-dubai-s-toyota-building-tenants-have-left-after-powe-f5a2e/']
  ],checks:['Compare registered or evidenced rent, not only asking rent.','Model vacancy, leasing fees, maintenance and service charges.','Read payment-product fees and eligibility conditions.','Treat building management and utility reliability as property-level risks.']},
  {slug:'dubai-developer-sales-tracker-2026',title:'Dubai Developer Sales Tracker 2026',description:'A consolidated tracker for Dubai developer sales, backlog, launch performance and the project-level checks behind company headlines.',kicker:'Developer sales and execution',intro:'Company sales and sell-out headlines can signal demand, but they do not prove that every unit is well priced or every project has the same risk. This tracker consolidates the strongest updates and links them back to buyer checks.',updates:[
    ['15 Aug 2026','Dubai was reported to have attracted 186 new property developers','/blog/property-news-2026-08-15-how-to-read-the-latest-dubai-property-market-signal-3e09d/'],
    ['14 Aug 2026','Zoya Developments reported selling out Elinor in under two weeks','/blog/property-news-2026-08-14-how-to-read-the-latest-dubai-property-market-signal-96e5c/'],
    ['7 Aug 2026','Emaar reported AED 26.6bn sales and AED 164.9bn backlog','/blog/property-news-2026-08-07-how-to-read-the-latest-dubai-property-market-signal-ff568/'],
    ['7 Aug 2026','Emaar Development reported AED 22.4bn sales and profit growth','/blog/property-news-2026-08-07-dubai-housing-supply-what-buyers-and-owners-should-check-n-76b75/']
  ],checks:['Separate reservation volume, booked sales, revenue and cash collection.','Review delivery record and current construction at project level.','Compare price per area, payment timing and finished-product quality.','Do not interpret company-wide momentum as guaranteed project performance.']}
];

const propertyNewsState=JSON.parse(fs.readFileSync(path.join(ROOT,'data/property-news-state.json'),'utf8'));
const originalSourceByPath=new Map((propertyNewsState.posts||[]).map(post=>[`/blog/${post.slug}/`,post.source_url]).filter(([,source])=>source));

const consolidated=new Set(trackers.flatMap(t=>t.updates.map(u=>u[2])));
const consolidatedTargets=new Map(trackers.flatMap(t=>t.updates.map(u=>[u[2],`/insights/${t.slug}/`])));
const articleMoves=new Map([
  ['property-news-2026-08-06-how-to-read-the-latest-dubai-property-market-signal-5cfed','trump-tower-dubai-construction-phase-2026'],
  ['property-news-2026-08-06-sharjah-homebuyer-update-a-practical-decision-checklist-d84dc','sharjah-property-deals-aed-7bn-july-2026'],
  ['property-news-2026-08-07-uae-housing-supply-what-buyers-and-owners-should-check-nex-6f2f1','damac-uae-bank-mortgage-event-buyers'],
  ['property-news-2026-08-10-dubai-housing-supply-what-buyers-and-owners-should-check-n-5f565','dubai-zoo-site-90-home-community'],
  ['property-news-2026-08-12-how-to-read-the-latest-dubai-property-market-signal-21f76','moodys-binghatti-ratings-regional-risk'],
  ['property-news-2026-08-13-how-to-read-the-latest-abu-dhabi-property-market-signal-abda4','uae-top-developers-aed-113bn-sales-2026'],
  ['property-news-2026-08-17-reading-the-latest-dubai-luxury-property-signal-9428c','nakheel-jebel-ali-village-892-home-handover'],
  ['property-news-2026-08-19-golden-visa-first-time-buyer-support-flexi-rent-how-dubai-99a12','dubai-property-access-first-time-buyers-renters']
]);
function esc(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function ensureDir(file){fs.mkdirSync(path.dirname(file),{recursive:true});}
function write(rel,content){const file=path.join(ROOT,rel);ensureDir(file);fs.writeFileSync(file,content.endsWith('\n')?content:content+'\n');}
function current(pathname,href){if(href==='/blog/')return pathname.startsWith('/blog/')||pathname.startsWith('/insights/');return pathname===href||pathname.startsWith(href)&&href!=='/';}
function nav(pathname){
  const link=(href,label)=>`<a href="${href}"${current(pathname,href)?' aria-current="page"':''}>${label}</a>`;
  const marketCurrent=['/dubai-data/','/abu-dhabi-data/','/ajman-data/','/dubai-rental-yield-calculator/','/dubai-property-buying-cost-calculator/'].some(h=>current(pathname,h));
  const flow=`${link('/buy-invest-dubai/','Buy')}${link('/sell-dubai-property/','Sell')}${link('/properties/','Projects')}${link('/areas/','Areas')}<details class="goal-nav market-data-nav${marketCurrent?' is-current':''}" data-menu-name="Market Data"><summary aria-label="Market Data menu">Market Data <span class="goal-nav-caret" aria-hidden="true">⌄</span></summary><div class="goal-nav-menu market-data-menu" role="group" aria-label="Market data and calculators">${link('/dubai-data/','Dubai')}${link('/abu-dhabi-data/','Abu Dhabi')}${link('/ajman-data/','Ajman')}${link('/dubai-rental-yield-calculator/','Yield Calculator')}${link('/dubai-property-buying-cost-calculator/','Buying Costs')}</div></details>${link('/blog/','Insights')}${link('/about-me/','About')}${link('/contact/','Contact')}`;
  return `<header class="site-header"><nav class="nav-shell" aria-label="Main navigation"><a class="brand" href="/" aria-label="James Realty">James Realty</a><div class="nav-links global-links">${flow}</div><a class="button nav-cta nav-whatsapp" href="/buy-invest-dubai/#buyer-enquiry">Build my buyer brief <span aria-hidden="true">→</span></a></nav></header><nav class="mobile-page-tabs section-shell" aria-label="Site navigation">${flow}</nav>`;
}
const footer=`<a class="mobile-conversion nav-whatsapp" href="/contact/?goal=buy">Start property brief</a><footer><div class="section-shell footer-shell footer-shell-rich"><div class="footer-identity"><a class="brand" href="/">James Realty</a><p>Evidence-led Dubai property advisory.<br>Dubai, UAE · © 2026 James.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="/buy-invest-dubai/">Buy</a><a href="/sell-dubai-property/">Sell</a><a href="/properties/">Projects</a><a href="/areas/">Areas</a><a href="/dubai-data/">Market Data</a><a href="/blog/">Insights</a><a href="/about-me/">About</a><a href="/contact/">Contact</a><a href="https://digital.jamesrealty.uk/" target="_blank" rel="noopener">Digital Services ↗</a><a href="/privacy-policy/">Privacy</a><a href="/terms/">Terms</a><a href="/disclaimer/">Disclaimer</a><a href="/sitemap.xml">Sitemap</a><a href="/data-methodology/">Data Methodology</a><a href="/editorial-methodology/">Editorial Methodology</a></nav><a class="footer-linkedin" href="https://ae.linkedin.com/in/james-ravi-dubai" target="_blank" rel="me noreferrer">LinkedIn <span aria-hidden="true">↗</span></a></div></footer>`;
const gtmHead=`<!-- Google Tag Manager --><script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src='https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);})(window,document,'script','dataLayer','GTM-M74SL57L');</script>`;
const gtmBody=`<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M74SL57L" height="0" width="0" style="display:none;visibility:hidden" title="Google Tag Manager"></iframe></noscript>`;
function head({title,description,pathname,image='/images/james-realty-dubai-advisory-social-v2.jpg',schema=[],scripts=[]}){
  const url=SITE+pathname;
  const graph=[{"@type":"WebSite","@id":SITE+'/#website',url:SITE+'/',name:'James Realty',description:'Evidence-led Dubai property advisory and market intelligence.',inLanguage:'en-AE'},{"@type":"Organization","@id":SITE+'/#organization',name:'James Realty',url:SITE+'/',founder:{"@type":"Person",name:'James',url:SITE+'/about-me/'},areaServed:{"@type":"City",name:'Dubai'}}].concat(schema);
  return `${gtmHead}<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1,max-video-preview:-1"><link rel="canonical" href="${url}"><link rel="icon" href="/favicon.svg"><link rel="apple-touch-icon" href="/favicon-192.png"><link rel="manifest" href="/site.webmanifest"><meta name="theme-color" content="#090919"><meta property="og:type" content="website"><meta property="og:site_name" content="James Realty"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="${SITE+image}"><meta name="twitter:card" content="summary_large_image"><script type="application/ld+json">${JSON.stringify({"@context":"https://schema.org","@graph":graph})}</script><link rel="stylesheet" href="/_next/static/css/5576f66c8ff02a6a.css?v=13"><link rel="stylesheet" href="/assets/advisory-platform.css?v=${VERSION}"><script defer src="/assets/site.js?v=${VERSION}"></script><script defer src="/assets/property-leads.js?v=${VERSION}"></script>${scripts.map(src=>`<script defer src="${src}?v=${VERSION}"></script>`).join('')}`;
}
function page(meta,body,{bodyClass='advisory-page',scripts=[]}={}){return `<!doctype html><html lang="en-AE"><head>${head({...meta,scripts})}</head><body class="${bodyClass}">${gtmBody}<a class="skip-link" href="#main-content">Skip to main content</a>${nav(meta.pathname)}<main id="main-content">${body}</main>${footer}</body></html>`;}
function hero({kicker,title,copy,primary,secondary,image,caption,tags=[]}){return `<section class="section-shell advisory-hero"><div class="advisory-hero-copy"><p class="eyebrow">${esc(kicker)}</p><h1>${esc(title)}</h1><p class="hero-description">${esc(copy)}</p><div class="advisory-actions"><a class="button button-primary" href="${primary.href}">${primary.label} <span aria-hidden="true">→</span></a><a class="button button-outline" href="${secondary.href}">${secondary.label}</a></div><ul class="advisory-proofline">${tags.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></div><figure class="advisory-media"><img src="${image}" width="1200" height="800" fetchpriority="high" decoding="async" alt="${esc(caption)}"><figcaption><span class="section-kicker">Evidence-led advisory</span><strong>${esc(caption)}</strong></figcaption></figure></section>`;}

function projectCard(p,heading='h2'){return `<article class="project-card" data-project-card="${esc(p.name)}" data-developer="${esc(p.developer)}" data-location="${esc(p.location)}" data-stage="${esc(p.stage)}" data-type="${esc(p.type)}" data-budget="${esc(p.budget)}"><div class="project-image"><img src="${p.image}" width="724" height="543" loading="lazy" decoding="async" alt="Representative ${esc(p.name)} research image"><span class="project-status">${esc(p.status)}</span></div><div class="project-copy"><span class="area-label">${esc(p.developer)} · ${esc(p.location)}</span><${heading}>${esc(p.name)}</${heading}><p>${esc(p.why)}</p><dl class="project-facts"><div><dt>Starting price</dt><dd>${esc(p.price)}</dd></div><div><dt>Status</dt><dd>${esc(p.stage)}</dd></div><div><dt>Property type</dt><dd>${esc(p.type.replace('|',' / '))}</dd></div><div><dt>Handover</dt><dd>${esc(p.handover)}</dd></div></dl><div class="project-assessment"><p><strong>Potential weakness:</strong> ${esc(p.risk)}</p><p><strong>Suitable buyer:</strong> ${esc(p.buyer)}</p></div><div class="project-actions"><a class="button button-primary" href="/contact/?goal=buy&project=${encodeURIComponent(p.name)}">Check availability</a><a class="button button-outline" href="${p.source}" target="_blank" rel="noopener noreferrer">Developer research ↗</a></div><p class="project-source">Source: James Realty developer research. Last reviewed ${UPDATED}. Availability is never assumed.</p></div></article>`;}

function buildHome(){
  const body=hero({kicker:'Dubai property advisory',title:'Dubai property decisions backed by market evidence.',copy:'Compare projects, communities, costs and market data before you shortlist. James Realty supports buyers, investors and sellers with direct, evidence-led decision support from Dubai.',primary:{href:'/properties/',label:'Explore Properties'},secondary:{href:'/buy-invest-dubai/#buyer-enquiry',label:'Build My Buyer Brief'},image:'/images/visuals/home-property-intelligence-1200.webp',caption:'Research, compare and shortlist with market context before making an enquiry.',tags:['Dubai based','Direct advisory','Project comparison','Clear risk discussion']})+
  `<section class="section-shell advisory-section"><div class="advisory-heading"><div><p class="section-kicker">Start with the decision</p><h2>Property first. Evidence before promotion.</h2></div><p>Use a focused journey for buying, comparing projects, researching communities or preparing a sale. Digital marketing services now sit separately at James Digital.</p></div><div class="advisory-grid"><a class="advisory-card" href="/buy-invest-dubai/"><span>Buy</span><h3>Define the right Dubai property brief.</h3><p>Clarify purpose, usable budget, finance, property type, preferred areas and timeline.</p><strong>Build a buyer brief →</strong></a><a class="advisory-card" href="/properties/"><span>Projects</span><h3>Compare projects on the same evidence.</h3><p>Review developer, location, published price, delivery context, potential weaknesses and buyer fit.</p><strong>Explore projects →</strong></a><a class="advisory-card" href="/areas/"><span>Areas</span><h3>Choose the community before the unit.</h3><p>Compare transport, schools, supply, service-charge context, strengths and trade-offs.</p><strong>Research areas →</strong></a><a class="advisory-card" href="/sell-dubai-property/"><span>Sell</span><h3>Prepare the facts before going to market.</h3><p>Organise ownership, tenancy, access, property condition, pricing evidence and launch priorities.</p><strong>Request a sale review →</strong></a></div></section>`+
  `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="advisory-heading"><div><p class="section-kicker">Visitor journey</p><h2>Research → Compare → Shortlist → Contact James</h2></div><p>The website is structured to reduce noise, not maximise the number of projects shown.</p></div><div class="decision-path"><article><strong>Research</strong><p>Start with official data, costs and area context.</p></article><article><strong>Compare</strong><p>Use the same criteria across ready and off-plan options.</p></article><article><strong>Shortlist</strong><p>Keep only the opportunities that fit the buyer brief.</p></article><article><strong>Contact James</strong><p>Send a securely captured requirement for direct follow-up.</p></article></div></div></section>`+
  `<section class="section-shell advisory-section"><div class="advisory-heading"><div><p class="section-kicker">Featured project research</p><h2>Opportunities to review, not stale inventory.</h2></div><p>Published prices and project information are reference points. Current availability is verified before any recommendation.</p></div><div class="project-grid">${projects.slice(0,3).map(p=>projectCard(p,'h3')).join('')}</div><div class="advisory-actions"><a class="button button-primary" href="/properties/">View all project research</a></div></section>`+
  `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="advisory-heading"><div><p class="section-kicker">Market data and tools</p><h2>Test the decision with evidence.</h2></div><p>Use cached and official-source market data, then calculate buying costs or net rental yield before shortlisting.</p></div><div class="advisory-grid"><a class="advisory-card" href="/dubai-data/"><span>Market Data</span><h3>Dubai Data</h3><p>Transaction activity, median prices, area comparisons, rental context and budget screens.</p><strong>Open Dubai Data →</strong></a><a class="advisory-card" href="/dubai-rental-yield-calculator/"><span>Calculator</span><h3>Rental Yield</h3><p>Compare gross and net income assumptions for two Dubai properties.</p><strong>Compare yield →</strong></a><a class="advisory-card" href="/dubai-property-buying-cost-calculator/"><span>Calculator</span><h3>Buying Costs</h3><p>Estimate acquisition fees and total upfront cash requirements.</p><strong>Estimate costs →</strong></a><a class="advisory-card" href="/insights/dubai-property-supply-tracker-2026/"><span>Tracker</span><h3>Dubai Supply 2026</h3><p>Consolidated reporting on completions, future supply and buyer implications.</p><strong>Open tracker →</strong></a></div></div></section>`+
  `<section class="section-shell advisory-section"><div class="trust-band"><div><p class="section-kicker">Why James Realty</p><h2>Direct advisory with the weaknesses kept visible.</h2><p>No guaranteed returns, no invented live inventory and no project recommendation based only on brand language.</p></div><ul><li>Dubai based and available to international buyers</li><li>Market-data backed project and community screening</li><li>Developer comparison and direct risk discussion</li><li>One direct point of communication</li></ul></div></section>`+
  `<section class="section-shell home-final"><div><p class="section-kicker">Start with a usable requirement</p><h2>Build your Dubai property shortlist.</h2><p>Share your budget, purpose, preferred areas and timeline. Your enquiry is securely captured before WhatsApp opens.</p></div><a class="button button-primary" href="/buy-invest-dubai/#buyer-enquiry">Build My Buyer Brief <span aria-hidden="true">→</span></a></section>`;
  const schema=[{"@type":"WebPage","@id":SITE+'/#webpage',url:SITE+'/',name:'Dubai Property Decisions Backed by Market Evidence',dateModified:UPDATED,isPartOf:{"@id":SITE+'/#website'}},{"@type":"ItemList",name:'James Realty property journeys',itemListElement:[['Buy',SITE+'/buy-invest-dubai/'],['Projects',SITE+'/properties/'],['Areas',SITE+'/areas/'],['Sell',SITE+'/sell-dubai-property/']].map(([name,item],i)=>({"@type":"ListItem",position:i+1,name,item}))}];
  write('index.html',page({title:'Dubai Property Advisory & Market Evidence | James Realty',description:'Evidence-led Dubai property advisory for buyers, investors and sellers. Compare projects, areas, market data, costs and risks before you shortlist.',pathname:'/',schema},body));
}

function buildProperties(){
  const body=hero({kicker:'Projects and properties',title:'Compare Dubai property opportunities without assuming live inventory.',copy:'This directory organises developer research into a consistent decision format. Use the filters to screen projects, then verify the exact unit, price, payment plan and availability before progressing.',primary:{href:'#project-directory',label:'Explore Projects'},secondary:{href:'/buy-invest-dubai/#buyer-enquiry',label:'Build My Buyer Brief'},image:'/images/dubai-residential-portfolio.webp',caption:'Developer portfolios translated into comparable buyer evidence.',tags:['Availability verified on request','Published references dated','Potential weaknesses shown','No guaranteed returns']})+
  `<section id="project-directory" class="section-shell directory-shell advisory-section" data-project-directory><div class="advisory-heading"><div><p class="section-kicker">Project directory</p><h2>Filter the research, then verify the unit.</h2></div><p>Price references come from existing James Realty developer research and do not guarantee a currently available unit.</p></div><div class="directory-controls"><label>Developer<select data-filter="developer"><option value="">All developers</option>${[...new Set(projects.map(p=>p.developer))].map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Location<select data-filter="location"><option value="">All locations</option>${[...new Set(projects.map(p=>p.location))].map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Status<select data-filter="stage"><option value="">Ready and off-plan</option><option>Ready</option><option>Off-plan</option></select></label><label>Property type<select data-filter="type"><option value="">All property types</option><option>Apartment</option><option>Townhouse</option><option>Villa</option></select></label><label>Published budget reference<select data-filter="budget"><option value="">All / on request</option><option value="under-1m">Below AED 1m</option><option value="1-2m">AED 1m–2m</option><option value="2-5m">AED 2m–5m</option><option value="on-request">Availability on request</option></select></label><div class="directory-summary"><span data-result-count></span><button class="directory-reset" type="button" data-directory-reset>Reset filters</button></div></div><div class="project-grid">${projects.map(p=>projectCard(p)).join('')}</div><p class="directory-empty" data-directory-empty hidden>No project profile matches every selected filter. Reset one filter or send a buyer brief for a wider market search.</p></section>`+
  `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="trust-band"><div><p class="section-kicker">Evidence standard</p><h2>What “check availability” means here.</h2><p>James Realty does not present a historical launch page as a live listing. A current check should confirm the developer or authorised seller, exact unit, price, payment schedule, fees, construction position and reservation terms.</p></div><ul><li>Source and last-reviewed date shown</li><li>Potential weakness included on every profile</li><li>Published starting price treated as a reference only</li><li>Unit-level documents required before a decision</li></ul></div></div></section>`;
  const schema=[{"@type":"CollectionPage","@id":SITE+'/properties/#webpage',url:SITE+'/properties/',name:'Dubai Projects and Properties',description:'Evidence-led project comparison directory.',dateModified:UPDATED,isPartOf:{"@id":SITE+'/#website'}},{"@type":"ItemList",numberOfItems:projects.length,itemListElement:projects.map((p,i)=>({"@type":"ListItem",position:i+1,name:p.name,url:p.source}))}];
  write('properties/index.html',page({title:'Dubai Projects & Properties to Review | James Realty',description:'Compare Dubai developer projects by location, status and property type, with published references, potential weaknesses, buyer fit and availability on request.',pathname:'/properties/',schema,scripts:['/assets/property-directory.js']},body,{scripts:['/assets/property-directory.js']}));
}

function buildAreas(){
  const cards=areas.map(a=>`<a class="area-card" href="/areas/${a.slug}/"><img src="${a.image}" width="800" height="520" loading="lazy" decoding="async" alt="${esc(a.name)} property and community context"><div><span class="area-label">${esc(a.label)}</span><h2>${esc(a.name)}</h2><p>${esc(a.profile)}</p><strong>Research this area →</strong></div></a>`).join('');
  const body=hero({kicker:'Dubai areas',title:'Choose the community before you choose the property.',copy:'Compare how Dubai areas work for the buyer’s purpose, budget, commute, schools, ownership costs and future supply. Community averages are context, not a substitute for building and unit evidence.',primary:{href:'#area-directory',label:'Explore Areas'},secondary:{href:'/dubai-data/#area-lookup',label:'Open Dubai Data'},image:'/images/dubai-community-buying-guide.webp',caption:'Area research connected to data, projects and practical buyer checks.',tags:['Pros and cons','Transport and schools','Supply context','Service-charge checks']})+
  `<section id="area-directory" class="section-shell advisory-section"><div class="advisory-heading"><div><p class="section-kicker">Priority communities</p><h2>Six different Dubai buying contexts.</h2></div><p>Each page links the area decision to market data, project research, calculators and a context-specific enquiry.</p></div><div class="area-grid">${cards}</div></section>`+
  `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="decision-path"><article><strong>Purpose</strong><p>End use, rental income, relocation or long-hold wealth preservation.</p></article><article><strong>Area evidence</strong><p>Transaction depth, rental context, supply and community maturity.</p></article><article><strong>Building evidence</strong><p>Developer, age, service charges, facilities and maintenance.</p></article><article><strong>Unit evidence</strong><p>Layout, view, floor, condition, tenancy and true total cost.</p></article></div></div></section>`;
  write('areas/index.html',page({title:'Dubai Areas & Community Research | James Realty',description:'Compare Dubai Marina, Downtown, Business Bay, Dubai Hills, JVC and Palm Jumeirah using buyer fit, transport, schools, supply, costs, pros and cons.',pathname:'/areas/',schema:[{"@type":"CollectionPage",url:SITE+'/areas/',name:'Dubai Areas and Community Research',dateModified:UPDATED},{"@type":"ItemList",itemListElement:areas.map((a,i)=>({"@type":"ListItem",position:i+1,name:a.name,url:SITE+'/areas/'+a.slug+'/'}))}]},body));
  for(const a of areas){
    const facts=[['Who it suits',a.profile],['Transport',a.transport],['Schools and family use',a.schools],['Upcoming and competing supply',a.supply],['Service-charge considerations',a.charges]];
    const areaBody=hero({kicker:a.label,title:`${a.name} property: who it suits, what to compare and where the risks sit.`,copy:`Use this ${a.name} guide to screen the community before reviewing a specific building or unit. Market figures should be checked against the latest Dubai Data and mapped carefully to official area names.`,primary:{href:'/contact/?goal=buy&area='+encodeURIComponent(a.name),label:'See Opportunities Here'},secondary:{href:'/dubai-data/#area-lookup',label:'Check Market Data'},image:a.image,caption:`${a.name} community and property decision context.`,tags:['Buyer profile','Transport','Supply','Pros and cons']})+
    `<section class="section-shell advisory-section"><div class="advisory-heading"><div><p class="section-kicker">Community assessment</p><h2>What matters in ${esc(a.name)}.</h2></div><p>Do not apply a district average to every tower, plot or unit. Use area data as the first screen, then move to property-level evidence.</p></div><div class="area-facts">${facts.map(([h,p])=>`<article><h3>${esc(h)}</h3><p>${esc(p)}</p></article>`).join('')}<article><h3>Pros</h3><ul>${a.pros.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article><article><h3>Cons</h3><ul>${a.cons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article></div><p class="area-data-notice"><strong>Data note:</strong> Dubai Land Department and third-party datasets can use administrative area names that differ from familiar community names. Confirm the mapping, date window, sample size and property type before treating a median or yield as relevant.</p></section>`+
    `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="advisory-grid"><a class="advisory-card" href="/dubai-data/#area-lookup"><span>Market Data</span><h3>Check area evidence</h3><p>Review transaction activity, median values, rental context and sample size.</p><strong>Open Dubai Data →</strong></a><a class="advisory-card" href="/properties/"><span>Projects</span><h3>Compare current research</h3><p>Filter developer and location profiles without assuming live inventory.</p><strong>Explore projects →</strong></a><a class="advisory-card" href="/dubai-rental-yield-calculator/"><span>Calculator</span><h3>Model net yield</h3><p>Include vacancy, service charges, maintenance and acquisition costs.</p><strong>Calculate yield →</strong></a><a class="advisory-card" href="/contact/?goal=buy&area=${encodeURIComponent(a.name)}"><span>Shortlist</span><h3>See opportunities here</h3><p>Send a securely captured requirement for direct follow-up.</p><strong>Start area brief →</strong></a></div></div></section>`;
    write(`areas/${a.slug}/index.html`,page({title:`${a.name} Property Guide: Pros, Cons & Buyer Fit | James Realty`,description:`Evidence-led ${a.name} property guide covering buyer fit, transport, schools, supply, service charges, pros, cons and links to Dubai market data.`,pathname:`/areas/${a.slug}/`,image:a.image,schema:[{"@type":"WebPage",url:SITE+`/areas/${a.slug}/`,name:`${a.name} Property Guide`,dateModified:UPDATED,about:{"@type":"Place",name:a.name}},{"@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:'Home',item:SITE+'/'},{"@type":"ListItem",position:2,name:'Areas',item:SITE+'/areas/'},{"@type":"ListItem",position:3,name:a.name,item:SITE+`/areas/${a.slug}/`}]}]},areaBody));
  }
}

function buildTrackers(){
  for(const t of trackers){
    const body=hero({kicker:t.kicker,title:t.title+'.',copy:t.intro,primary:{href:'#tracker-updates',label:'Review Updates'},secondary:{href:'/editorial-methodology/',label:'Editorial Methodology'},image:'/images/dubai-community-buying-guide.webp',caption:'Related reporting consolidated into one maintained decision resource.',tags:['Selective publishing','Direct source links','Buyer implications','Updated over time']})+
    `<section id="tracker-updates" class="section-shell advisory-section"><div class="advisory-heading"><div><p class="section-kicker">Consolidated updates</p><h2>What changed and why it matters.</h2></div><p>Older story URLs redirect here where the topic is better served by one maintained resource.</p></div><div class="tracker-updates">${t.updates.map(([date,title,url])=>`<article class="tracker-update"><time>${date}</time><div><span class="tracker-label">Market Monitoring Brief</span><h3>${esc(title)}</h3><p>Read the underlying source-led analysis, then test the implications against the specific area, project and unit.</p></div><a href="${esc(originalSourceByPath.get(url)||url)}" target="_blank" rel="noopener">Original source ↗</a></article>`).join('')}</div></section>`+
    `<section class="advisory-section advisory-section-alt"><div class="section-shell"><div class="trust-band"><div><p class="section-kicker">Decision checks</p><h2>Do not stop at the headline.</h2><p>${esc(t.description)}</p></div><ul>${t.checks.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div></div></section>`;
    write(`insights/${t.slug}/index.html`,page({title:`${t.title} | James Realty`,description:t.description,pathname:`/insights/${t.slug}/`,schema:[{"@type":"CollectionPage",url:SITE+`/insights/${t.slug}/`,name:t.title,description:t.description,dateModified:UPDATED}]},body));
  }
}

function buildMethods(){
  const pages=[
    ['data-methodology','Data Methodology','How James Realty sources, caches, labels and limits UAE property-market data.','James Realty presents public and official-source property data for research and screening. Data can be delayed, revised, mapped differently or incomplete. Each dashboard should show its source and the latest successful retrieval date.','Use area-level figures as context, not a valuation for an individual property. Check date windows, sample size, property type, official area naming and whether a figure is a median, total or modelled yield. If a live source fails, the site should show the latest successful cached dataset and its retrieval date.'],
    ['editorial-methodology','Editorial Methodology','How source monitoring, selective publication, consolidation and corrections work on James Realty.','Automation assists with monitoring public property sources. It does not make automation the editorial product. A report should be published only when it adds material buyer, seller or investor context.','Related stories are consolidated into maintained tracker pages where that produces more authority and less repetition. Reader-facing articles link to the source, separate reported facts from James Realty analysis, avoid guaranteed-return language and identify limitations. Material URL changes use one-step permanent redirects.'],
    ['disclaimer','Property & Data Disclaimer','Important limits on property information, market data, calculations and project availability.','James Realty content is general information and decision support, not legal, tax, financial, valuation or guaranteed investment advice.','Prices, payment plans, availability, handover dates, service charges, rental assumptions and regulatory information can change. Verify the exact unit, seller or developer authority, contract, escrow, construction status, fees, title position and professional advice relevant to your circumstances. Market data and calculators are estimates, not promises of return.'],
    ['terms','Website Terms','Terms governing the use of JamesRealty.uk and its research tools.','By using this website, you agree to use the information as general research and decision support.','You remain responsible for independent due diligence and professional advice. Do not rely on the site as a live listing inventory, formal valuation, legal opinion or guaranteed investment recommendation. Site content may be corrected, consolidated, updated or redirected to maintain accuracy and topical authority.'],
  ];
  for(const [slug,title,description,intro,detail] of pages){
    const body=`<section class="section-shell advisory-section method-card"><p class="eyebrow">James Realty policy</p><h1>${esc(title)}</h1><p class="hero-description">${esc(intro)}</p><h2>How to use this information</h2><p>${esc(detail)}</p><h2>Questions or corrections</h2><p>Email <a href="mailto:james@jamesrealty.uk?subject=${encodeURIComponent(title+' question')}">james@jamesrealty.uk</a> or use the <a href="/contact/">contact page</a>. Last updated ${UPDATED}.</p></section>`;
    write(`${slug}/index.html`,page({title:`${title} | James Realty`,description,pathname:`/${slug}/`,schema:[{"@type":"WebPage",url:SITE+`/${slug}/`,name:title,dateModified:UPDATED}]},body));
  }
}

function buildPrivacy(){
  const body=`<section class="section-shell advisory-section method-card"><p class="eyebrow">Privacy and data</p><h1>Privacy Policy.</h1><p class="hero-description">How James Realty collects, uses and protects property-enquiry, attribution, analytics and website data.</p><h2>What is collected</h2><p>With your consent, a property enquiry may include your name, phone or WhatsApp number, email, country, budget, preferences, notes, page of origin, referral information and campaign parameters. The form is securely stored before WhatsApp opens so a request is not lost if that handoff is interrupted.</p><h2>How it is used</h2><p>Enquiry data is used to respond, prepare a relevant property shortlist, verify current information, operate the advisory relationship, prevent abuse and measure website effectiveness. James Realty does not sell personal data. WhatsApp, email and analytics providers apply their own terms when you use those services.</p><h2>Storage, retention and security</h2><p>Submitted lead records are stored through secured website infrastructure and kept only as long as reasonably necessary for the advisory purpose, recordkeeping, security and legal obligations. A temporary safety copy may remain in the submitting browser until a failed request is successfully retried. Access is limited to people and systems that need it, but no internet system can be guaranteed completely secure.</p><h2>Your choices</h2><p>You may ask to access, correct or delete personal information controlled by James Realty, or withdraw consent to future contact. Some records may be retained where law or legitimate recordkeeping requires it. Please do not send passports, bank details or sensitive documents through a general enquiry form.</p><h2>Contact</h2><p>Email <a href="mailto:james@jamesrealty.uk?subject=Privacy%20request">james@jamesrealty.uk</a> or use the <a href="/contact/">contact page</a>. Last updated ${UPDATED}.</p></section>`;
  write('privacy-policy/index.html',page({title:'Privacy Policy | James Realty',description:'How James Realty collects, stores, uses and protects property-enquiry, analytics and website data.',pathname:'/privacy-policy/',schema:[{"@type":"WebPage",url:SITE+'/privacy-policy/',name:'James Realty Privacy Policy',dateModified:UPDATED}]},body));
}

function updateExisting(){
  const replacements=[
    ['UAE Property & Real Estate Marketing | James Realty','Dubai Property Advisory & Market Evidence | James Realty'],
    ['Automated brief','Market Monitoring Brief'],
    ['automated brief','market monitoring brief']
  ];
  for(const file of fs.readdirSync(path.join(ROOT,'blog'),{recursive:true}).filter(f=>String(f).endsWith('.html'))){
    const full=path.join(ROOT,'blog',file);let text=fs.readFileSync(full,'utf8');for(const [from,to] of replacements)text=text.split(from).join(to);fs.writeFileSync(full,text);
  }
  const simplePages=['buy-invest-dubai/index.html','sell-dubai-property/index.html','contact/index.html','about-me/index.html'];
  for(const rel of simplePages){
    const file=path.join(ROOT,rel);let text=fs.readFileSync(file,'utf8');
    if(!text.includes('/assets/advisory-platform.css'))text=text.replace('</head>',`<link rel="stylesheet" href="/assets/advisory-platform.css?v=${VERSION}"><script defer src="/assets/property-leads.js?v=${VERSION}"></script></head>`);
    text=text.replace(/The details are not stored on this website\./g,'Your details are securely captured before WhatsApp opens, with your consent.')
      .replace(/No information is stored on this website\./g,'Your details are securely captured before WhatsApp opens, with your consent.')
      .replace(/The form does not send data to a database\. It opens WhatsApp with your structured enquiry, which you can edit before sending\./g,'With your consent, the form securely saves the enquiry before opening WhatsApp so your request is not lost.')
      .replace(/Private, browser based/g,'Secure pre-WhatsApp capture')
      .replace(/Marketing Strategy · Brand Leadership · Performance Acquisition/g,'Dubai Property Advisory · Market Research · Project Comparison')
      .replace(/Marketing leader with deep experience in UAE real estate, luxury brand building, and performance acquisition\. Proven across complex property launches, global investor campaigns, and CRM-led conversion\./g,'Dubai-based property adviser combining real-estate experience, developer knowledge and market research to help buyers, investors and sellers make clearer decisions. Direct support is available for UAE and international clients.')
      .replace(/Making paid media accountable after the lead arrives\./g,'Helping buyers compare Dubai property with clearer evidence.')
      .replace(/I connect campaign data with CRM outcomes so budget decisions reflect contactability, qualification, and sales follow-up, not form volume alone\./g,'I connect the buyer brief with market data, community context, developer comparison, project-level checks and direct discussion of the trade-offs.')
      .replace(/Contact James/g,'Speak with James')
      .replace('About James Ravi | Luxury Real Estate Marketing Leader','About James Ravi | Dubai Property Adviser & Market Research')
      .replace('<meta property="og:title" content="About James Ravi | Luxury Real Estate Marketing Leader"/>','<meta property="og:title" content="About James Ravi | Dubai Property Adviser & Market Research"/>')
      .replace('About James Ravi: expertise, selected work, measurable results, career experience and global brand portfolio in luxury real estate marketing.','Meet James Ravi, a Dubai-based property adviser using market research, developer knowledge and real-estate experience to support clearer buyer and seller decisions.')
      .replace('James Ravi’s experience in luxury property launches, performance acquisition, brand strategy, and CRM-led conversion.','Dubai property advice informed by project-launch, developer, market-research and international buyer experience.')
      .replace('Portrait of James Ravi, Dubai real-estate marketing leader','Portrait of James Ravi, Dubai property adviser')
      .replace('"jobTitle":"Luxury Real Estate Marketing Leader"','"jobTitle":"Dubai Property Adviser"')
      .replace('"contactType":"business enquiries"','"contactType":"property enquiries"')
      .replace('Senior marketing leadership across luxury real estate, global launches, performance acquisition, and CRM-led growth.','Dubai property advice informed by senior real-estate marketing leadership, developer experience and international buyer campaigns.')
      .replace('From brand strategy to signed demand.','Property judgment informed by how projects are built, launched and sold.')
      .replace('One integrated marketing discipline covering luxury positioning, global launches, acquisition, investor communications, CRM, and sales conversion.','The advisory approach combines community and project research with a practical understanding of developer positioning, buyer behaviour, delivery, demand and resale competition.')
      .replace('Need a launch plan or a cleaner route from lead to sale?','Need a clearer Dubai property shortlist?')
      .replace('Share the project, priority market, and the part of the funnel that needs attention.','Share your purpose, budget, preferred areas, property type and timeline.');
    if(rel==='contact/index.html'){
      if(!text.includes('name="phone"'))text=text.replace('<label>Email<input name="email" type="email" autocomplete="email" placeholder="name@email.com"/></label>','<label>Email<input name="email" type="email" autocomplete="email" placeholder="name@email.com"/></label><label>Phone / WhatsApp *<input name="phone" type="tel" autocomplete="tel" inputmode="tel" required placeholder="+971 50 000 0000"/></label>');
      if(!text.includes('property-lead-consent'))text=text.replace('<div class="contact-goal-submit">','<label class="property-lead-consent full"><input name="consent" type="checkbox" required><span>I agree that James Realty may securely store and use this enquiry to respond and provide property decision support. See the <a href="/privacy-policy/">Privacy Policy</a>.</span></label><div class="contact-goal-submit">');
      if(!text.includes('class="contact-options"'))text=text.replace('<div class="contact-goal-direct">',`<div class="contact-options"><a href="https://wa.me/971528420933" target="_blank" rel="noopener noreferrer"><span>WhatsApp</span><strong>Chat with James</strong></a><a href="mailto:james@jamesrealty.uk?subject=Property%20enquiry"><span>Email</span><strong>james@jamesrealty.uk</strong></a><a href="mailto:james@jamesrealty.uk?subject=Property%20call%20request"><span>Book a Call</span><strong>Request a time</strong></a><a href="#contact-goal-form"><span>Property Requirement</span><strong>Send your brief</strong></a></div><div class="contact-goal-direct">`);
      text=text.replace(/<label class="contact-goal-option"><input[^>]+value="marketing"[\s\S]*?<\/label>/,'')
        .replace('<input type="radio" name="goal" value="marketing" hidden/>','')
        .replace(/<div class="contact-goal-panel contact-dynamic-grid" data-goal-panel="marketing" hidden>[\s\S]*?<\/div>/,'')
        .replace('Choose whether you want to buy or invest, sell a property, or discuss real estate marketing. The form changes to match your goal and prepares a structured WhatsApp message for review.','Choose whether you want to buy or invest or sell a property. The form changes to match your goal and securely captures the requirement before opening WhatsApp.')
        .replace('The enquiry remains private in your browser until WhatsApp opens. No account, database or third-party form platform is used.','With your consent, the enquiry is securely stored before WhatsApp opens, then sent to James for direct follow-up.')
        .replace('<li>Campaign, lead generation and CRM briefs</li>','<li>Market-data and project-comparison questions</li>')
        .replace('<a href="/real-estate-marketing/"><span>Marketing guide</span><strong>How campaigns, lead generation and CRM work together</strong></a>','<a href="https://digital.jamesrealty.uk/" target="_blank" rel="noopener"><span>Separate service</span><strong>Real estate marketing at James Digital ↗</strong></a>')
        .replace('Choose Buy or Invest for a property search, Sell for an owner enquiry, or Marketing for campaigns, lead generation, CRM and conversion support.','Choose Buy or Invest for a property search or Sell for an owner enquiry. Real estate marketing is handled separately through James Digital.')
        .replace('No. The form prepares a WhatsApp message locally in your browser. You review and send the message through WhatsApp.','With your consent, the website securely stores the enquiry before opening WhatsApp. This prevents the requirement being lost if the handoff is interrupted.')
        .replace(/<meta name="description" content="[^"]*real estate marketing[^"]*"\/>/,'<meta name="description" content="Speak directly with James Realty about buying, investing in or selling Dubai property."/>')
        .replace('contactType":"property and marketing enquiries"','contactType":"property enquiries"')
        .replace('<title>Speak with James Realty | Buy, Sell or Real Estate Marketing</title>','<title>Contact James Realty | Buy or Sell Dubai Property</title>')
        .replace('Speak with James Realty | Buy, Sell or Real Estate Marketing','Contact James Realty | Buy or Sell Dubai Property')
        .replace('Choose your goal and create a focused WhatsApp brief for a Dubai property or real estate marketing enquiry.','Send a securely captured Dubai property buyer or seller brief before continuing on WhatsApp.')
        .replace('Start a focused buyer, seller or real estate marketing enquiry.','Start a focused Dubai property buyer or seller enquiry.')
        .replace('Speak with James Realty about buying, investing, selling or real estate marketing.','Speak with James Realty about buying, investing in or selling Dubai property.')
        .replace('"dateModified":"2026-08-02"','"dateModified":"2026-09-01"')
        .replace(',{"@type":"ListItem","position":3,"url":"https://jamesrealty.uk/real-estate-marketing/","name":"Real estate marketing, lead generation and CRM"}','')
        .replace('The form creates a structured WhatsApp message that the visitor can review before sending. The website does not store the form details.','With consent, the website securely stores the property enquiry before opening a structured WhatsApp message.')
        .replace('Choose Buy or Invest for a Dubai property search, Sell for an owner enquiry, or Marketing for campaigns, lead generation, CRM and conversion support.','Choose Buy or Invest for a Dubai property search or Sell for an owner enquiry. Marketing services are separate at James Digital.')
        .replace(',{"@type":"Question","name":"Can international property and investor campaigns be discussed?","acceptedAnswer":{"@type":"Answer","text":"Yes. The marketing form includes target market, campaign requirement, media budget and timeline fields for UAE and international campaigns."}}','');
    }
    text=text.replace(/^[ \t]+$/gm,'');
    fs.writeFileSync(file,text);
  }
}

function updateSitemap(){
  const file=path.join(ROOT,'sitemap.xml');let xml=fs.readFileSync(file,'utf8');
  for(const url of consolidated){const escaped=(SITE+url).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');xml=xml.replace(new RegExp(`\\s*<url>\\s*<loc>${escaped}<\\/loc>[\\s\\S]*?<\\/url>`,'g'),'');}
  for(const pathname of ['/','/buy-invest-dubai/','/sell-dubai-property/','/dubai-data/','/abu-dhabi-data/','/ajman-data/','/blog/','/about-me/','/contact/','/privacy-policy/']){
    const escaped=(SITE+pathname).replace(/[.*+?^${}()|[\]\\]/g,'\\$&');
    xml=xml.replace(new RegExp(`(<loc>${escaped}<\\/loc>\\s*<lastmod>)[^<]+`),`$1${UPDATED}`);
  }
  xml=xml.replace(/<loc>https:\/\/jamesrealty\.uk\/blog\/property-news\/<\/loc>\s*<lastmod>[^<]+<\/lastmod>\s*<changefreq>hourly<\/changefreq>/,'<loc>https://jamesrealty.uk/blog/property-news/</loc>\n    <lastmod>2026-09-01</lastmod>\n    <changefreq>weekly</changefreq>');
  const urls=[['/properties/','weekly','1.0'],['/areas/','weekly','1.0'],...areas.map(a=>[`/areas/${a.slug}/`,'monthly','0.9']),...trackers.map(t=>[`/insights/${t.slug}/`,'weekly','0.9']),['/data-methodology/','yearly','0.5'],['/editorial-methodology/','yearly','0.5'],['/disclaimer/','yearly','0.4'],['/terms/','yearly','0.4']];
  const additions=urls.filter(([pathname])=>!xml.includes(`<loc>${SITE+pathname}</loc>`)).map(([pathname,freq,priority])=>`  <url>\n    <loc>${SITE+pathname}</loc>\n    <lastmod>${UPDATED}</lastmod>\n    <changefreq>${freq}</changefreq>\n    <priority>${priority}</priority>\n  </url>`).join('\n');
  if(additions)xml=xml.replace('</urlset>',additions+'\n</urlset>');
  xml=xml.replace(/\n{2,}<\/urlset>/,'\n</urlset>');fs.writeFileSync(file,xml);
}

function updateInternalRedirectLinks(){
  function walk(directory){
    for(const entry of fs.readdirSync(directory,{withFileTypes:true})){
      if(entry.name==='.git'||entry.name==='node_modules')continue;
      const full=path.join(directory,entry.name);
      if(entry.isDirectory()){walk(full);continue;}
      if(!entry.name.endsWith('.html'))continue;
      let html=fs.readFileSync(full,'utf8');
      for(const [oldPath,target] of consolidatedTargets){
        html=html.split(`href="${oldPath}"`).join(`href="${target}"`)
          .split(`href='${oldPath}'`).join(`href='${target}'`);
      }
      for(const [oldSlug,newSlug] of articleMoves){
        const oldPath=`/blog/${oldSlug}/`;const target=`/blog/${newSlug}/`;
        html=html.split(`href="${oldPath}"`).join(`href="${target}"`)
          .split(`href='${oldPath}'`).join(`href='${target}'`);
      }
      fs.writeFileSync(full,html);
    }
  }
  walk(ROOT);
}

function migrateArticleUrls(){
  for(const [oldSlug,newSlug] of articleMoves){
    const oldFile=path.join(ROOT,'blog',oldSlug,'index.html');
    if(!fs.existsSync(oldFile))continue;
    const oldPath=`/blog/${oldSlug}/`;const newPath=`/blog/${newSlug}/`;
    const migrated=fs.readFileSync(oldFile,'utf8').split(SITE+oldPath).join(SITE+newPath).split(`href="${oldPath}"`).join(`href="${newPath}"`).split(`href='${oldPath}'`).join(`href='${newPath}'`);
    write(`blog/${newSlug}/index.html`,migrated);
  }
  for(const rel of ['sitemap.xml','image-sitemap.xml','feed.xml']){
    const file=path.join(ROOT,rel);if(!fs.existsSync(file))continue;
    let text=fs.readFileSync(file,'utf8');
    for(const [oldSlug,newSlug] of articleMoves)text=text.split(`/blog/${oldSlug}/`).join(`/blog/${newSlug}/`);
    fs.writeFileSync(file,text);
  }
  const stateFile=path.join(ROOT,'data/property-news-state.json');
  const state=JSON.parse(fs.readFileSync(stateFile,'utf8'));
  for(const post of state.posts||[]){if(articleMoves.has(post.slug))post.slug=articleMoves.get(post.slug);}
  fs.writeFileSync(stateFile,JSON.stringify(state,null,2)+'\n');
}

function updateDataMetadata(){
  for(const rel of ['dubai-data/index.html','abu-dhabi-data/index.html','ajman-data/index.html']){
    const file=path.join(ROOT,rel);
    const html=fs.readFileSync(file,'utf8').replace('"dateModified":"2026-08-02"','"dateModified":"2026-09-01"');
    fs.writeFileSync(file,html);
  }
}

function cleanCrossDomainAssets(){
  const file=path.join(ROOT,'digital/index.html');
  if(!fs.existsSync(file))return;
  const html=fs.readFileSync(file,'utf8').replace('<link rel="stylesheet" href="/assets/property-news.css?v=2"/>','');
  fs.writeFileSync(file,html);
}

buildHome();buildProperties();buildAreas();buildTrackers();buildMethods();buildPrivacy();updateExisting();migrateArticleUrls();updateSitemap();updateInternalRedirectLinks();updateDataMetadata();cleanCrossDomainAssets();
console.log(`Built property-first homepage, ${projects.length} project profiles, ${areas.length} area pages, ${trackers.length} trackers and policy pages.`);
